import type { Metadata } from 'next';
import { inter } from '@/lib/fonts';
import Header from '@/app/_components/header';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ja'>
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
